### ISSUE TITLE
Address `--noincompatible_disallow_empty_glob` that was added to `rules_xcodeproj` due to issue in `bzlformat_pkg.bzl`

### ISSUE THREAD

**Issue by cgrindel** [cgrindel/bazel-starlib#140]
`rules_xcodeproj` PR: https://github.com/buildbuddy-io/rules_xcodeproj/pull/380#discussion_r863010450

Related to buildbuddy-io/rules_xcodeproj#380

## Tasks
- [x] Update `bazel-starlib` to support flag. Will need to disable items related to `rules_nodejs` and `rules_bazel_integration_test`.
  - [x] Need to allow a client to specify the deps that they will use. Allows us to avoid items related to `rules_nodejs`. #141
  - [x] Temporarily disable targets that leverage `rules_nodejs`. #142
- [x] Create a `bazel-starlib` release.
- [x] Update `rules_bazel_integration_test` to support flag.  [bazel-contrib/rules_bazel_integration_test#160](https://github.com/bazel-contrib/rules_bazel_integration_test/pull/60)
  - [x] Update to use latest `bazel-starlib`
  - [x] Update to use latest `bazel-skylib`
- [x] Create a `rules_bazel_integration_test` release. [0.7.0](https://github.com/bazel-contrib/rules_bazel_integration_test/releases/tag/v0.7.0)
- [x] Update `rules_xcodeproj` to use latest `rules_bazel_integration_test`. buildbuddy-io/rules_xcodeproj#392
- [x] Update `bazel-starlib` to use latest `rules_bazel_integration_test`. #144 
- [ ] Update `rules_nodejs` to support flag.
  - [ ] May need to transition to use `rules_bazel_integration_test`
- [ ] Update `bazel-starlib` to use updated `rules_nodejs`
- [ ] Create a `bazel-starlib` release.

**Comment by cgrindel** [comment]
To enable flag:

```python
# Don't allow empty glob patterns by default
build --incompatible_disallow_empty_glob
```
