### ISSUE TITLE
Support `bzlmod`

### ISSUE THREAD

**Issue by cgrindel** [cgrindel/bazel-starlib#195]
## Tasks
- [x] #232 
- [x] #233
- [x] #237
- [x] #238
- [x] #240
- [x] #242
- [x] [Publish to BCR](https://github.com/bazel-contrib/publish-to-bcr)
  - [x] #234
  - [x] Create a release
- [x] Debug presubmit failure on BCR CI machines (bazelbuild/bazel#17738)
  - [x] #244
  - [x] #246
  - [x] #249
- [x] #248
- [x] #258 
  - [x] Enabled bzlmod in `shared.bazelrc`
  - [x] Enable the `doc_for_provs` declarations.
- [ ] #266
- [ ] Once bazelbuild/bazel#14140 is fixed.
  - [ ] #267
  - [ ] #268

**Comment by cgrindel** [comment]
Tracking remaining items in other issues.
