### ISSUE TITLE
Update `bzlrelease` to build a release archive

### ISSUE THREAD

**Issue by cgrindel** [cgrindel/bazel-starlib#200]
[Recent incident](https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1675104355343989)

## Tasks
- [x] Build a compressed archive of the files needed to use the repo. Use the `filegroup` called `local_repository_files` as it contains everything that is needed to execute code in the child workspaces.
- [x] Calculate the SHA256 for the archive.
- [x] Update the workspace snippets.
- [x] Upload the archive in the release action.
- [x] Delete `v0.11.1-beta` release and create release `v.0.12.0`.
