### ISSUE TITLE
Migrate `bazel-doc`, `bazel_shlib`, `rules_bzlformat` and `rules_updatesrc` to `bazel-starlib`

### ISSUE THREAD

**Issue by cgrindel** [cgrindel/bazel-starlib#44]
## Tasks
- [x] Migrate [bazel-doc](https://github.com/cgrindel/bazel-doc).
- [x] Set up the structure for bazel-starlib to accomodate all of the rulesets.
- [x] Migrate [rules_updatesrc](https://github.com/cgrindel/rules_updatesrc).
- [x] Migrate [rules_bzlformat](https://github.com/cgrindel/rules_bzlformat).
- [x] MIgrate [bazel_shlib](https://github.com/cgrindel/bazel_shlib).
- [x] Migrate all of the README to starlib.
- [x] Update rules_bazel_integration_test to use bazel-starlib.
- [x] Update rules_swiftformat to use bazel-starlib.
- [x] Update swift_toolbox to use bazel-starlib.
- [x] Update rules_spm to use bazel-starlib.
- [x] [bazel-doc](https://github.com/cgrindel/bazel-doc): Update to point to new home.
- [x] [bazel_shlib](https://github.com/cgrindel/bazel_shlib): Update to point to new home.
- [x] [rules_updatesrc](https://github.com/cgrindel/rules_updatesrc): Update to point to new home.
- [x] [rules_bzlformat](https://github.com/cgrindel/rules_bzlformat): Update to point to new home.
